### ISSUE TITLE
NPE on player tracker in a reloaded world

### ISSUE THREAD

**Issue by Cervator** [Terasology/Cities#28] opened 2015-11-07 21:56 UTC
Seems something doesn't save/load right. The player tracking for city enter/exit (I think?) works fine on first creation of a world, but if you then save and reload player movement causes NPEs:

```
16:49:56.684 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
    at org.terasology.cities.events.PlayerTracker.onEnterBlock(PlayerTracker.java:94) ~[na:na]
    at org.terasology.cities.events.PlayerTrackerMethodAccess.invoke(Unknown Source) ~[na:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:502) [classes/:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) [classes/:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) [classes/:na]
    at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) [classes/:na]
    at org.terasology.logic.characters.KinematicCharacterMover.checkBlockEntry(KinematicCharacterMover.java:152) [classes/:na]
    at org.terasology.logic.characters.KinematicCharacterMover.step(KinematicCharacterMover.java:106) [classes/:na]
    at org.terasology.logic.characters.ServerCharacterPredictionSystem.stepState(ServerCharacterPredictionSystem.java:145) [classes/:na]
    at org.terasology.logic.characters.ServerCharacterPredictionSystem.onPlayerInput(ServerCharacterPredictionSystem.java:129) [classes/:na]
    at org.terasology.logic.characters.ServerCharacterPredictionSystemMethodAccess.invoke(Unknown Source) [reflectasm-1.11.0.jar:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:502) [classes/:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) [classes/:na]
    at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) [classes/:na]
    at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) [classes/:na]
    at org.terasology.logic.players.LocalPlayerSystem.processInput(LocalPlayerSystem.java:154) [classes/:na]
    at org.terasology.logic.players.LocalPlayerSystem.update(LocalPlayerSystem.java:126) [classes/:na]
    at org.terasology.engine.modes.StateIngame.update(StateIngame.java:178) [classes/:na]
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) [classes/:na]
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) [classes/:na]
    at org.terasology.engine.Terasology.main(Terasology.java:154) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
16:49:56.686 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
```

Seems fairly easy to reproduce (I stayed inside whatever city I spawned in the whole time). Doesn't crash the game or cause much trouble but it sure fills up the log in a hurry if you're moving around :-)
##

**Comment by Cervator** [comment] 2015-11-08 20:29
Saw it happen on an initial create as well, on entering a third city or so. Was flying with hspeed on so I might have momentarily overtaken world gen. Some issue with triggering something when the world isn't ready for it?

In any case once triggered it remains constant on any movement.

**Comment by msteiger** [comment] 2015-11-10 17:25
Thanks for the report. I cannot reproduce the issue. One related issue was fixed a week or two ago, but this is probably not it. Is the stacktrace still the same for you?

**Comment by Cervator** [comment] 2015-11-10 21:05
Yep. I went and tried the latest release (8 days old) and it is present that way too.

Odd that it isn't as reproducible as I expected. Can you try with the binary?

Tried to test in latest dev build but that's broken, whoops. Need to rebuild some modules to get that Region3i update fully in place.

**Comment by Cervator** [comment] 2015-11-10 21:42
Fixed latest Omega. Happens there as well for me.

**Comment by skaldarnar** [comment] 2015-11-10 23:33
Reproducible on my site with latest Omega. Basically the same stack trace...

**Comment by jdrueckert** [comment] 2022-05-08 17:45
Seems to have been fixed by now.

**Closed by jdrueckert** 2022-05-08 17:45 UTC
Labels: Type: Bug
